
enum ActionType {

INIT = 'devices/INIT',

GET_DEVICES_START = 'devices/GET_DEVICES_START',
GET_DEVICES_SUCCESS = 'devices/GET_DEVICES_SUCCESS',
GET_DEVICES_FAILED = 'devices/GET_DEVICES_FAILED',

CLICK_NOTIFY_BUTTON = 'devices/CLICK_NOTIFY_BUTTON'

}


export default ActionType